production:
  # path to the root directory that stores the page files
  wiki_path: wikirep

  # set this to false for a read-only wiki. Useful with Blogki

  editable: false

  # enable this option to use an external style sheet

  # cssHref http://www.my.domain/stylesheet.css

  # enable this option to have the wiki rendered in a template. See the
  # sample.template.htm file for how to use this option. (NOTE: this is a
  # BETA option -- probably not even a sample.template.htm included in the
  # distribution)

  # template: mytemplate.htm

  # If you want to restrict the Recent view to only published pages, you
  # can configure a custom tag here. If this isn't defined, then every
  # page will appear on the Recent view.
  #
  # publishTag: <publish>

  # showSourceLink can be turned on to add a page link in the footer that
  # is a file:// url direct to the raw page. Default is false.
  #
  # showSourceLink: true

  # time format for display of last page update
  #
  page_update_format: '%B %d, %Y'

  # Add directories containing optional custom formatters here.
  #
  custom_formatter_load_path: []

  # Require a user account to access the wiki. Defaults to false.
  #
  # use_authentication: false

test:
  wiki_path: tmp/testrep
  editable: true
  page_update_format: '%B %d, %Y'
  custom_formatter_load_path: []

development:
  # path to the root directory that stores the page files
  wiki_path: wikirep
  editable: true
  page_update_format: '%B %d, %Y'
  custom_formatter_load_path: []
